Repository llaverowallet/llavero, pull requests merged in 2024-05, with the labels that each got.

#109 first try sign windows
  .github/workflows/windows-installer.yml
  apps/desktop/package.json
  apps/desktop/tools/forge/forge.config.js
  apps/web/package.json
  package.json
Labels: size:M

#113 fix rpcs
  apps/web/src/app/api/accounts/services/get-wallet.ts
  apps/web/src/app/api/accounts/services/list-wallets.ts
  apps/web/src/app/api/wallet/services/eth-send-tx.ts
  apps/web/src/app/api/wallet/services/eth-sign-tx.ts
  apps/web/src/app/api/wallet/services/eth-sign-typed.ts
  apps/web/src/app/api/wallet/services/personal-sign.ts
  apps/web/src/data/EIP155Data.ts
  apps/web/src/features/accounts/components/account-menu.tsx
  apps/web/src/features/accounts/components/account-sections/account-activity.tsx
  apps/web/src/features/accounts/components/send-dialog.tsx
  apps/web/src/features/accounts/hooks/use-transactions.ts
  apps/web/src/features/accounts/index.tsx
  apps/web/src/repositories/user-table-init.ts
  apps/web/src/shared/components/header/index.tsx
  yarn.lock
Labels: size:L

#119 Sign Windows GA and delete obsolete packages
  .github/workflows/windows-installer.yml
  apps/home/.eslintrc.json
  apps/home/.gitignore
  apps/home/README.md
  apps/home/next.config.js
  apps/home/package.json
  apps/home/postcss.config.js
  apps/home/public/next.svg
  apps/home/public/vercel.svg
  apps/home/src/app/api/install/route.ts
  apps/home/src/app/favicon.ico
  apps/home/src/app/globals.css
  apps/home/src/app/layout.tsx
  apps/home/src/app/page.tsx
  apps/home/tailwind.config.ts
  apps/home/tsconfig.json
  packages/cdk-cloudvault/.gitignore
  packages/cdk-cloudvault/.npmignore
  packages/cdk-cloudvault/README.md
  packages/cdk-cloudvault/bin/cdk-cloudvault.ts
  packages/cdk-cloudvault/cdk.json
  packages/cdk-cloudvault/jest.config.js
  packages/cdk-cloudvault/lib/cdk-cloudvault-stack.ts
  packages/cdk-cloudvault/package.json
  packages/cdk-cloudvault/test/cdk-cloudvault.test.ts
  packages/cdk-cloudvault/tsconfig.json
  packages/codedeploy/.gitignore
  packages/codedeploy/.npmignore
  packages/codedeploy/README.md
  packages/codedeploy/bin/codedeploy.ts
  packages/codedeploy/cdk.json
  packages/codedeploy/jest.config.js
  packages/codedeploy/lib/codedeploy-stack.ts
  packages/codedeploy/package.json
  packages/codedeploy/test/codedeploy.test.ts
  packages/codedeploy/tsconfig.json
  packages/installer/package.json
  packages/installer/sst-deploy.ts
  packages/installer/tsconfig.json
  yarn.lock
Labels: size:XL

#121 linux installer
  .github/workflows/linux-installer.yml
Labels: size:S

#122 Update linux-installer.yml
  .github/workflows/linux-installer.yml
Labels: size:XS
